services:
  postgres:
    image: postgres:16.3-alpine
    container_name: ado_postgres_dev
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ado_dev
    restart: unless-stopped
    hostname: postgres.local

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ado_web_dev
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-postgres}@postgres.local:5432/prisma
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    ports:
      - 3000:3000
      - 5555:5555 # For Prisma Studio
    networks:
      - ado_dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    hostname: ado.local
    stdin_open: true # Keep the container running
    tty: true

networks:
  ado_dev:
    driver: bridge

volumes:
  postgres-data:
  node_modules:
