export const timelineConfig = [
  // 2017
  "kimi-no-taion",
  "star-night-show",
  "strangers",
  "shinkonsui",

  // 2018
  "watashino-aru",
  "kirai-kirai",
  "bad-dance-hall",
  "uminaoshi",
  "renai-saiban",
  "akushidento-coordinator",
  "merutirando-nightmare",
  "adishonaru-memory",
  "ego-rock-short",

  // 2019
  "otome-kaibou",
  "secret-answer",
  "nounai-kakumei-girl",
  "ai-oyobi-yau",
  "jama",
  "hungry-nicole",
  "bin",
  "basket-worm",

  // 2020
  "usseewa",
  "last-resort",
  "bokkaderaberita",
  "baka",
  "hysteric-night-girl",
  "hanshoku-no-kansho",
  "limbo",
  "sunny-wave",
  "black-rock-shooter",

  // 2021
  "readymade",
  "gira-gira",
  "odo",
  "yoru-no-pierrot",
  "anti-system",
  "aitakute",
  "snow-song-show",
  "ashura-chan",
  "kimi-no-taion-2021",
  "renai-senso",
  "16-bit-girl",
  "daze",
  "zaneri",
  "yokubari",
  "adam-to-eve",
  "shizahands",

  // 2022
  "motherland",
  "lucky-bruto",
  "new-genesis",
  "backlight",
  "im-invincible",
  "fleeting-lullaby",
  "binkusuno-sake",
  "world-continuation",
  "tot-musica",
  "where-wind-blows",
  "rebellion",
  "missing",
  "freedom",
  "wonderful-cat-life",
  "love-and-destroy",
  "kokoro-fukakai",
  "fireworks",
  "darling-dance",
  "tokyo-wa-yoru",
  "birthday-song-for-miku",
  "inojinaroshi",

  // 2023
  "atashi-wa-mondaisaku",
  "ibara",
  "himawari",
  "show",
  "dignity",
  "kura-kura",
  "all-night-radio",
  "hello-signals",
  "atashi-i-my-risoron",
  "shinjinrui",
  "interviewer",

  // 2024
  "value",
  "mirror",
  "rule",
  "zero",
  "chocolat-cadabra",
  "sakura-biyori-time-machine",
  "shoka",
  "episode-x",
  "nukegara",
  "lazy-cruise",
  "sugarvine",

  // 2025
  "elf",
  "bouquet-for-me",
  "rockstar",
  "cats-eye",
];
